### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by espidev** [vik1395/ProtectionStones-Minecraft#42]
Using Creative Commons for code is highly not recommended: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by Seshpenguin** [comment]
The GPL is a good alternative to the current CreativeCommons.

Edit upon further reading, you may not be able to convert the licences. The NoCommerical clause makes this GPL incompatible (https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses)

**Comment by Dragoboss** [comment]
https://www.spigotmc.org/wiki/public-license/
Honestly license wise I do not care, as long as its fully compatible with Spigot's standards.
I am not going to spend too much time reading through loads of legal mumbo-jumbo in order to find what to switch to and what's allowed.
If you want to, go ahead and pull-request me afterwards.

**Comment by Seshpenguin** [comment]
@Dragoboss Yea it is not possible to switch the licence anyway with the current one.
