### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by ghost** [vik1395/ProtectionStones-Minecraft#9]
I need version to 1.10.2, please!!!
Java 8!

In 1.10.2 Java 8 the regions are not saved when you restart the sv, help please.

**Comment by ghost** [comment]
Hey

It might help if you write what version you are currently using + worldguard version and such.

Hard to bug trace things with this little information for the developers.

**Comment by ghost** [comment]
Last version of everything.

**Comment by Dragoboss** [comment]
Now this explains a lot.
As of WorldGuard 6.1.3, the way flags are handled has changed in WorldGuard.
Since most people use stable versions of WorldGuard rather than developer releases such as the one I assume you are using, we have not referenced these changes in the main version of ProtectionStones yet. However we have made a branch on our Github with a version that applies this change.

_**For those using WorldGuard 6.1.3+, please use the following ProtectionStones versions:**_
https://github.com/vik1395/ProtectionStones-Minecraft/tree/WorldGuard_6.1.3/target

I have also posted this into the ProtectionStones thread on Spigotmc.org

**Comment by Dragoboss** [comment]
Duplicate issue #3
